# SPDX-License-Identifier: MIT-0
---
galaxy_info:
  author: Mahesh Babu Derangula
  description: Install and configure NGINX on RHEL hosts.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "9"
  galaxy_tags:
    - nginx
    - rhel
    - webserver
dependencies: []
