---
- name: Platform Engineering AWX Connection Test
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Verify AWX Execution
      ansible.builtin.debug:
        msg: "GitOps 2.0! AWX automatically synced the project and ran the latest code."
